import CategorySecond from "../../../icons/CategorySecond";
import CategoryFirst from "../../../icons/CategoryFirst";
import CategoryThird from "../../../icons/CategoryThird";
import CategoryFourth from "../../../icons/CategotyFourth";

const sites = [
  {
    id: 0,
    avatar: "path",
    author: "Andrew Jonson",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "STARTUP",
    title: "Design tips for designers that cover everything you need",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategorySecond />,
  },
  {
    id: 1,
    avatar: "path",
    author: "Andrew Stockton",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "BUSINESS",
    title: "How to build rapport with your web design clients",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryFirst />,
  },
  {
    id: 2,
    avatar: "path",
    author: "Andrew Shevchenko",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "STARTUP",
    title: "Logo design trends to avoid in 2022",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategorySecond />,
  },
  {
    id: 3,
    avatar: "path",
    author: "Mykhailo Jonson",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "TECHNOLOGY",
    title: "8 Figma design systems you can download for free today",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryFourth />,
  },
  {
    id: 4,
    avatar: "path",
    author: "Michael Jordan",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "ECONOMY",
    title: "Font sizes in UI design: The complete guide to follow",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryThird />,
  },
  {
    id: 5,
    avatar: "path",
    author: "Bred Pitt",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "TECHNOLOGY",
    title: "8 Figma design systems you can download for free today",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryFourth />,
  },
  {
    id: 6,
    avatar: "path",
    author: "Andrew Khtozna",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "STARTUP",
    title: "Logo design trends to avoid in 2022",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategorySecond />,
  },
  {
    id: 7,
    avatar: "path",
    author: "Andrew theBest",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "ECONOMY",
    title: "Font sizes in UI design: The complete guide to follow",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryThird />,
  },
  {
    id: 8,
    avatar: "path",
    author: "Lebron Jonson",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "ECONOMY",
    title: "Font sizes in UI design: The complete guide to follow",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryThird />,
  },
  {
    id: 9,
    avatar: "path",
    author: "Andrew Whigger",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "ECONOMY",
    title: "Font sizes in UI design: The complete guide to follow",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryThird />,
  },
  {
    id: 10,
    avatar: "path",
    author: "Subota Wednesday",
    date: "Posted on 27th January 2022",
    fullImg: "path",
    picture: "path",
    category: "ECONOMY",
    title: "Font sizes in UI design: The complete guide to follow",
    text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
    blog: "text",
    icon: <CategoryThird />,
  },
];
export default sites;
